# Generated by Django 6.0.2 on 2026-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0ne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableone',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
